format = """
$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$username\
$sudo\
$character\
"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$time\
"""

add_newline = true

[character]
error_symbol   = "[ï‘§](purple)"
format         = "$symbol "
success_symbol = "[ó°·](bold blue)"

[env_var.VIMSHELL] # vim subshell
format = "[$env_value]($style)"
style  = 'green'

[username]
disabled   = false
format     = "[$user]($style) â–» "
style_root = "purple bold"
style_user = "yellow bold"

[directory]
format            = ' [$path]($style)[$read_only]($read_only_style)'
home_symbol       = "~"
read_only         = " ó°Œ¾"
truncation_length = 2
truncation_symbol = "ï“ "

[cmd_duration]
format   = "[$duration ](bright-yellow)"
min_time = 500

[jobs]
format = "[ $symbol$number]($style)"
style  = "white"
symbol = "[â–¶ ](blue)"

[localip]
disabled = false
format   = " â—¯[$localipv4](bold magenta)"
ssh_only = true

[time]
disabled        = false
format          = "[ $time]($style)"
style           = "dimmed white"
time_format     = "%R"
utc_time_offset = "local"

[battery]
charging_symbol    = "[â†‘](green)"
discharging_symbol = "[â†“]()"
empty_symbol       = "[â–ƒ](red)"
format             = "[ $percentage $symbol]($style)"
full_symbol        = "[â–ˆ](green)"
unknown_symbol     = "[â–‘]()"

    [[battery.display]]
    style     = "dimmed yellow"
    threshold = 40

    [[battery.display]]
    style     = "dimmed white"
    threshold = 70

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style)"
style  = "bold 5"
symbol = "[ï˜](bold 5)"

[git_status]
style = "fg:5"
# format = """([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"""
# conflicted = "ó±ƒŸ"
# ahead  = "îª ${count}"
# behind = "îª${count}"
# diverged = "[îª ${ahead_count}îª${behind_count}](cyan)"
# diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
# untracked = "â—Œâ—¦"
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
# staged = '[++\($count\)](green)'
# renamed = "R"
# deleted = "[âœ•](italic red)"

[deno]
format         = " deno [âˆ« $version](blue)"
version_format = "${major}.${minor}"

[lua]
format = " [${symbol}${version}]($style)"
style  = "bright-yellow"
symbol = "î˜  "

[nodejs]
detect_files = ["package-lock.json", "yarn.lock"]
format       = " [${symbol}($version)](green)"
symbol       = "îœ˜ "
# version_format = "${major}.${minor}"

[python]
format         = " [${symbol}${version}]($style)"
style          = "bright-yellow"
symbol         = "[îˆµ](bright-blue) "
version_format = "${major}.${minor}"

[ruby]
format         = " [${symbol}${version}]($style)"
style          = "red"
symbol         = "î‘ "
version_format = "${major}.${minor}"

[rust]
format         = " [$symbol$version]($style)"
style          = "red"
symbol         = "î¨ "
version_format = "${major}.${minor}"

[package]
format         = " [$symbol$version]($style)"
style          = "bright-yellow"
symbol         = "ó°— "
version_format = "${major}.${minor}"

[swift]
format         = " sw [${symbol}${version}]($style)"
style          = "bright-red"
symbol         = "â— "
version_format = "${major}.${minor}"

[aws]
format = " aws [$symbol $profile $region]($style)"
style  = "blue"
symbol = "îŒ½  "

[buf]
format = " [$symbol$version $buf_version]($style)"
symbol = "ï’ "

[c]
format = " $symbol($version(-$name))]($style)"
symbol = "î˜ "

[conda]
format = " [$symbol$environment]($style)"
symbol = "ï„Œ "

[dart]
format = " [$symbol($version )]($style)"
symbol = "î˜ "

[docker_context]
format = " [$symbol$context]($style)"
symbol = "ïŒˆ "

[elixir]
format = " [$symbol $version OTP $otp_version ]($style)"
symbol = "î‰µ "

[elm]
format = " [$symbol($version )]($style)"
symbol = "î˜¬ "

[golang]
format = " [$symbol($version )]($style)"
symbol = "î˜§ "

[haskell]
format = " [$symbol($version )]($style)"
symbol = "î· "

[java]
format = " [${symbol}(${version} )]($style)"
symbol = "î‰– "

[julia]
format = " [$symbol($version )]($style)"
symbol = "î˜¤ "

[memory_usage]
format = " [${ram}( ${swap})]($style)"
symbol = "ï¿½ "

[nim]
format = " [$symbol($version )]($style)"
symbol = "ó°†¥ "

[nix_shell]
format = " [$symbol$state $name]($style)"
symbol = "ïŒ“ "

[spack]
format = " spack [$symbol$environment]($style)"
symbol = "â—‡ "

[zig]
format = " [$symbol($version)]($style)"
symbol = "â†¯ "

[os]
disabled = true

    [os.symbols]
    Alpaquita        = "îª¢ "
    Alpine           = "ïŒ€ "
    Amazon           = "ï‰° "
    Android          = "ï…» "
    Arch             = "ïŒƒ "
    Artix            = "ïŒŸ "
    CentOS           = "ïŒ„ "
    Debian           = "ïŒ† "
    DragonFly        = "îŠ "
    Emscripten       = "ïˆ… "
    EndeavourOS      = "ï†— "
    Fedora           = "ïŒŠ "
    FreeBSD          = "ïŒŒ "
    Garuda           = "ó°›“ "
    Gentoo           = "ïŒ "
    HardenedBSD      = "ó°Œ "
    Illumos          = "ó°ˆ¸ "
    Linux            = "ïŒš "
    Mabox            = "î¬© "
    Macos            = "ïŒ‚ "
    Manjaro          = "ïŒ’ "
    Mariner          = "ï‡ "
    MidnightBSD      = "ï†† "
    Mint             = "ïŒ "
    NetBSD           = "ï€¤ "
    NixOS            = "ïŒ“ "
    OpenBSD          = "ó°ˆº "
    OracleLinux      = "ó°Œ· "
    Pop              = "ïŒª "
    Raspbian         = "ïŒ• "
    RedHatEnterprise = "ïŒ– "
    Redhat           = "ïŒ– "
    Redox            = "ó°€˜ "
    SUSE             = "ïŒ” "
    Solus            = "ó° ³ "
    Ubuntu           = "ïŒ› "
    Unknown          = "ïˆ­ "
    Windows          = "ó°² "
    openSUSE         = "ïŒ” "
